### ISSUE TITLE
Don`t read variable in python script

### ISSUE THREAD

**Issue by mikle7771** [Thomaash/me#444]
Example:
```
from mininet.net import Mininet
from mininet.link import Intf
from mininet.node import Controller, RemoteController
from mininet.cli import CLI

net = Mininet( topo=None, build=False )
intfName = 'eth1'
s3 = net.addSwitch( 's3' )
_intf = Intf( intfName, node=s3 )
```
When I do file import, in logs:
`Can't procces function call Intf( intfName, node=s3 )`

if you do: 
`_intf = Intf( 'eth1', node=s3 )`
interface will be created

**Comment by Thomaash** [comment]
Hi @mikle7771,

the code is not executed (i.e. no variable assignments happen), it's parsed and some data is then extracted. It's main purpose is to (partially) recover lost projects (where scripts still exist) and to import scripts from MiniEdit.
